
    create table incidents (
        id bigint generated by default as identity,
        reported_at timestamp(6),
        description varchar(1000) not null,
        severity varchar(255) not null,
        title varchar(255) not null,
        primary key (id)
    );

    create table incidents (
        id bigint generated by default as identity,
        reported_at timestamp(6),
        description varchar(1000) not null,
        severity varchar(255) not null,
        title varchar(255) not null,
        primary key (id)
    );
